language: java
dist: trust
jdk:
  - oraclejdk8
install: true
script:
  - git config --global user.email "wesleyvanneck105@outlook.com"
  - git config --global user.name "LegacyGamerHD"
 # - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
 # - java -jar BuildTools.jar --rev 1.14.4
  - chmod +x ./scripts/inst.sh
  - ./scripts/inst.sh --setup
after_success:
  - rm -rf push
  - mkdir push
  - cp ./target/*.jar ./push/
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $Github_token
  file:
    - ./push/*
  file_glob: true
  on:
    tags: true
